//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Действия.
    /// </summary>
    // *** Start programmer edit section *** (Действия CustomAttributes)

    // *** End programmer edit section *** (Действия CustomAttributes)
    public enum Действия
    {
        
        // *** Start programmer edit section *** (Действия.СделатьФото CustomAttributes)

        // *** End programmer edit section *** (Действия.СделатьФото CustomAttributes)
        [Caption("СделатьФото")]
        СделатьФото,
        
        // *** Start programmer edit section *** (Действия.Редактировать CustomAttributes)

        // *** End programmer edit section *** (Действия.Редактировать CustomAttributes)
        [Caption("Редактировать")]
        Редактировать,
        
        // *** Start programmer edit section *** (Действия.ПечатьФото CustomAttributes)

        // *** End programmer edit section *** (Действия.ПечатьФото CustomAttributes)
        [Caption("ПечатьФото")]
        ПечатьФото,
        
        // *** Start programmer edit section *** (Действия.ОтправитьНаФлеш CustomAttributes)

        // *** End programmer edit section *** (Действия.ОтправитьНаФлеш CustomAttributes)
        [Caption("ОтправитьНаФлеш")]
        ОтправитьНаФлеш,
    }
}
