//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ фото.
    /// </summary>
    // *** Start programmer edit section *** (ЗаказФото CustomAttributes)

    // *** End programmer edit section *** (ЗаказФото CustomAttributes)
    [AutoAltered()]
    [Caption("Заказ фото")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказФотоE", new string[] {
            "ДатаСоздания as \'Дата создания\'",
            "СпособОплаты as \'Способ оплаты\'"})]
    [AssociatedDetailViewAttribute("ЗаказФотоE", "Фото", "ФотоE", true, "", "Фото", true, new string[] {
            ""})]
    [View("ЗаказФотоL", new string[] {
            "ДатаСоздания as \'Дата создания\'",
            "СпособОплаты as \'Способ оплаты\'"})]
    public class ЗаказФото : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаСоздания = System.DateTime.Now;
        
        private IIS.Prilozhenie.ТипОплаты fСпособОплаты;
        
        private IIS.Prilozhenie.DetailArrayOfФото fФото;
        
        // *** Start programmer edit section *** (ЗаказФото CustomMembers)

        // *** End programmer edit section *** (ЗаказФото CustomMembers)

        
        /// <summary>
        /// ДатаСоздания.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказФото.ДатаСоздания CustomAttributes)

        // *** End programmer edit section *** (ЗаказФото.ДатаСоздания CustomAttributes)
        public virtual System.DateTime ДатаСоздания
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказФото.ДатаСоздания Get start)

                // *** End programmer edit section *** (ЗаказФото.ДатаСоздания Get start)
                System.DateTime result = this.fДатаСоздания;
                // *** Start programmer edit section *** (ЗаказФото.ДатаСоздания Get end)

                // *** End programmer edit section *** (ЗаказФото.ДатаСоздания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказФото.ДатаСоздания Set start)

                // *** End programmer edit section *** (ЗаказФото.ДатаСоздания Set start)
                this.fДатаСоздания = value;
                // *** Start programmer edit section *** (ЗаказФото.ДатаСоздания Set end)

                // *** End programmer edit section *** (ЗаказФото.ДатаСоздания Set end)
            }
        }
        
        /// <summary>
        /// СпособОплаты.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказФото.СпособОплаты CustomAttributes)

        // *** End programmer edit section *** (ЗаказФото.СпособОплаты CustomAttributes)
        public virtual IIS.Prilozhenie.ТипОплаты СпособОплаты
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказФото.СпособОплаты Get start)

                // *** End programmer edit section *** (ЗаказФото.СпособОплаты Get start)
                IIS.Prilozhenie.ТипОплаты result = this.fСпособОплаты;
                // *** Start programmer edit section *** (ЗаказФото.СпособОплаты Get end)

                // *** End programmer edit section *** (ЗаказФото.СпособОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказФото.СпособОплаты Set start)

                // *** End programmer edit section *** (ЗаказФото.СпособОплаты Set start)
                this.fСпособОплаты = value;
                // *** Start programmer edit section *** (ЗаказФото.СпособОплаты Set end)

                // *** End programmer edit section *** (ЗаказФото.СпособОплаты Set end)
            }
        }
        
        /// <summary>
        /// Заказ фото.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказФото.Фото CustomAttributes)

        // *** End programmer edit section *** (ЗаказФото.Фото CustomAttributes)
        public virtual IIS.Prilozhenie.DetailArrayOfФото Фото
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказФото.Фото Get start)

                // *** End programmer edit section *** (ЗаказФото.Фото Get start)
                if ((this.fФото == null))
                {
                    this.fФото = new IIS.Prilozhenie.DetailArrayOfФото(this);
                }
                IIS.Prilozhenie.DetailArrayOfФото result = this.fФото;
                // *** Start programmer edit section *** (ЗаказФото.Фото Get end)

                // *** End programmer edit section *** (ЗаказФото.Фото Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказФото.Фото Set start)

                // *** End programmer edit section *** (ЗаказФото.Фото Set start)
                this.fФото = value;
                // *** Start programmer edit section *** (ЗаказФото.Фото Set end)

                // *** End programmer edit section *** (ЗаказФото.Фото Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказФотоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказФотоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказФотоE", typeof(IIS.Prilozhenie.ЗаказФото));
                }
            }
            
            /// <summary>
            /// "ЗаказФотоL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказФотоL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказФотоL", typeof(IIS.Prilozhenie.ЗаказФото));
                }
            }
        }
    }
}
