//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип бумаги.
    /// </summary>
    // *** Start programmer edit section *** (ТипБумаги CustomAttributes)

    // *** End programmer edit section *** (ТипБумаги CustomAttributes)
    public enum ТипБумаги
    {
        
        // *** Start programmer edit section *** (ТипБумаги.Матовая CustomAttributes)

        // *** End programmer edit section *** (ТипБумаги.Матовая CustomAttributes)
        [Caption("Матовая")]
        Матовая,
        
        // *** Start programmer edit section *** (ТипБумаги.Глянцевая CustomAttributes)

        // *** End programmer edit section *** (ТипБумаги.Глянцевая CustomAttributes)
        [Caption("Глянцевая")]
        Глянцевая,
    }
}
