//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип оплаты.
    /// </summary>
    // *** Start programmer edit section *** (ТипОплаты CustomAttributes)

    // *** End programmer edit section *** (ТипОплаты CustomAttributes)
    public enum ТипОплаты
    {
        
        // *** Start programmer edit section *** (ТипОплаты.Наличный CustomAttributes)

        // *** End programmer edit section *** (ТипОплаты.Наличный CustomAttributes)
        [Caption("Наличный")]
        Наличный,
        
        // *** Start programmer edit section *** (ТипОплаты.Безналичный CustomAttributes)

        // *** End programmer edit section *** (ТипОплаты.Безналичный CustomAttributes)
        [Caption("Безналичный")]
        Безналичный,
    }
}
