//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Фото.
    /// </summary>
    // *** Start programmer edit section *** (Фото CustomAttributes)

    // *** End programmer edit section *** (Фото CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФотоE", new string[] {
            "Услуги as \'Услуги\'",
            "Услуги.Наименование as \'Наименование\'",
            "Услуги.Цена as \'Цена\'",
            "Количество as \'Количество\'",
            "КачествоБумаги as \'Качество бумаги\'",
            "ДействияСФото as \'Действия с фото\'"}, Hidden=new string[] {
            "Услуги.Наименование"})]
    [MasterViewDefineAttribute("ФотоE", "Услуги", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class Фото : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private IIS.Prilozhenie.ТипБумаги fКачествоБумаги;
        
        private IIS.Prilozhenie.Действия fДействияСФото;
        
        private IIS.Prilozhenie.Услуги fУслуги;
        
        private IIS.Prilozhenie.ЗаказФото fЗаказФото;
        
        // *** Start programmer edit section *** (Фото CustomMembers)

        // *** End programmer edit section *** (Фото CustomMembers)

        
        /// <summary>
        /// ДействияСФото.
        /// </summary>
        // *** Start programmer edit section *** (Фото.ДействияСФото CustomAttributes)

        // *** End programmer edit section *** (Фото.ДействияСФото CustomAttributes)
        public virtual IIS.Prilozhenie.Действия ДействияСФото
        {
            get
            {
                // *** Start programmer edit section *** (Фото.ДействияСФото Get start)

                // *** End programmer edit section *** (Фото.ДействияСФото Get start)
                IIS.Prilozhenie.Действия result = this.fДействияСФото;
                // *** Start programmer edit section *** (Фото.ДействияСФото Get end)

                // *** End programmer edit section *** (Фото.ДействияСФото Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Фото.ДействияСФото Set start)

                // *** End programmer edit section *** (Фото.ДействияСФото Set start)
                this.fДействияСФото = value;
                // *** Start programmer edit section *** (Фото.ДействияСФото Set end)

                // *** End programmer edit section *** (Фото.ДействияСФото Set end)
            }
        }
        
        /// <summary>
        /// КачествоБумаги.
        /// </summary>
        // *** Start programmer edit section *** (Фото.КачествоБумаги CustomAttributes)

        // *** End programmer edit section *** (Фото.КачествоБумаги CustomAttributes)
        public virtual IIS.Prilozhenie.ТипБумаги КачествоБумаги
        {
            get
            {
                // *** Start programmer edit section *** (Фото.КачествоБумаги Get start)

                // *** End programmer edit section *** (Фото.КачествоБумаги Get start)
                IIS.Prilozhenie.ТипБумаги result = this.fКачествоБумаги;
                // *** Start programmer edit section *** (Фото.КачествоБумаги Get end)

                // *** End programmer edit section *** (Фото.КачествоБумаги Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Фото.КачествоБумаги Set start)

                // *** End programmer edit section *** (Фото.КачествоБумаги Set start)
                this.fКачествоБумаги = value;
                // *** Start programmer edit section *** (Фото.КачествоБумаги Set end)

                // *** End programmer edit section *** (Фото.КачествоБумаги Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (Фото.Количество CustomAttributes)

        // *** End programmer edit section *** (Фото.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (Фото.Количество Get start)

                // *** End programmer edit section *** (Фото.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (Фото.Количество Get end)

                // *** End programmer edit section *** (Фото.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Фото.Количество Set start)

                // *** End programmer edit section *** (Фото.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (Фото.Количество Set end)

                // *** End programmer edit section *** (Фото.Количество Set end)
            }
        }
        
        /// <summary>
        /// Фото.
        /// </summary>
        // *** Start programmer edit section *** (Фото.Услуги CustomAttributes)

        // *** End programmer edit section *** (Фото.Услуги CustomAttributes)
        [PropertyStorage(new string[] {
                "Услуги"})]
        [NotNull()]
        public virtual IIS.Prilozhenie.Услуги Услуги
        {
            get
            {
                // *** Start programmer edit section *** (Фото.Услуги Get start)

                // *** End programmer edit section *** (Фото.Услуги Get start)
                IIS.Prilozhenie.Услуги result = this.fУслуги;
                // *** Start programmer edit section *** (Фото.Услуги Get end)

                // *** End programmer edit section *** (Фото.Услуги Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Фото.Услуги Set start)

                // *** End programmer edit section *** (Фото.Услуги Set start)
                this.fУслуги = value;
                // *** Start programmer edit section *** (Фото.Услуги Set end)

                // *** End programmer edit section *** (Фото.Услуги Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Prilozhenie.ЗаказФото.
        /// </summary>
        // *** Start programmer edit section *** (Фото.ЗаказФото CustomAttributes)

        // *** End programmer edit section *** (Фото.ЗаказФото CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ЗаказФото"})]
        public virtual IIS.Prilozhenie.ЗаказФото ЗаказФото
        {
            get
            {
                // *** Start programmer edit section *** (Фото.ЗаказФото Get start)

                // *** End programmer edit section *** (Фото.ЗаказФото Get start)
                IIS.Prilozhenie.ЗаказФото result = this.fЗаказФото;
                // *** Start programmer edit section *** (Фото.ЗаказФото Get end)

                // *** End programmer edit section *** (Фото.ЗаказФото Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Фото.ЗаказФото Set start)

                // *** End programmer edit section *** (Фото.ЗаказФото Set start)
                this.fЗаказФото = value;
                // *** Start programmer edit section *** (Фото.ЗаказФото Set end)

                // *** End programmer edit section *** (Фото.ЗаказФото Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФотоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФотоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФотоE", typeof(IIS.Prilozhenie.Фото));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Фото.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfФото CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfФото CustomAttributes)
    public class DetailArrayOfФото : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Prilozhenie.DetailArrayOfФото members)

        // *** End programmer edit section *** (IIS.Prilozhenie.DetailArrayOfФото members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Фото by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Фото.
        /// </summary>
        public DetailArrayOfФото(IIS.Prilozhenie.ЗаказФото fЗаказФото) : 
                base(typeof(Фото), ((ICSSoft.STORMNET.DataObject)(fЗаказФото)))
        {
        }
        
        public IIS.Prilozhenie.Фото this[int index]
        {
            get
            {
                return ((IIS.Prilozhenie.Фото)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Prilozhenie.Фото dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
